# ignore path during linting
excluded:
  - Pods

disabled_rules:
  - trailing_whitespace

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 200
  error: 400

type_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 4
  max_length:
    warning: 40
    error: 50

identifier_name:
  allowed_symbols: ["_"]
  excluded:
    - id
    - cv
    - vc
    - to
    - url
    - add
    - day
    - app
    - log
    - lhs
    - rhs
    - key
    - img
  min_length:
    warning: 4
  max_length:
    warning: 40
    error: 50

line_length:
  warning: 200
  error: 400

opt_in_rules:
  - force_unwrapping
  - conditional_returns_on_newline
  - private_outlet
  - vertical_whitespace
  - custom_rules

reporter: "xcode"

custom_rules:
    no_hard_coded_strings:
    regex: '^[^#][a-zA-Z0-9][a-zA-Z0-9! ]+'
    match_kinds:
      - string
    message: "Hard coded string is never a good practice"
    severity: warning
